import { PageHeader } from "@/components/PageHeader";
import { BulkTeamMappingReview, bulkMappingKey, type BulkTeamMappingGroup } from "@/components/BulkTeamMappingReview";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { downloadBase64File, readFileAsBase64 } from "@/lib/download";
import { trpc } from "@/lib/trpc";
import { ArchiveRestore, CheckCircle2, CircleAlert, Download, FileSpreadsheet, FileUp, History, Loader2, RefreshCw, Upload } from "lucide-react";
import { ChangeEvent, useRef, useState } from "react";
import { toast } from "sonner";

type ImportMode = "import" | "restore";

export default function DataManagementPage() {
  const [processing, setProcessing] = useState<ImportMode | null>(null);
  const [pendingBulkImport, setPendingBulkImport] = useState<{ base64: string; fileName: string; totalRows: number; groups: BulkTeamMappingGroup[] } | null>(null);
  const [teamMappings, setTeamMappings] = useState<Record<string, number>>({});
  const importInputRef = useRef<HTMLInputElement>(null);
  const restoreInputRef = useRef<HTMLInputElement>(null);
  const utils = trpc.useUtils();
  const templateQuery = trpc.excel.template.useQuery(undefined, { enabled: false });
  const exportQuery = trpc.excel.exportPersonnel.useQuery(undefined, { enabled: false });
  const importMutation = trpc.excel.importPersonnel.useMutation();
  const analyzeMappingsMutation = trpc.excel.analyzeTeamMappings.useMutation();
  const logMutation = trpc.backup.record.useMutation({ onSuccess: () => void utils.backup.listLogs.invalidate() });
  const { data: logs = [], isLoading: logsLoading } = trpc.backup.listLogs.useQuery();
  async function downloadTemplate() { const response = await templateQuery.refetch(); if (response.data) { downloadBase64File(response.data.base64, response.data.filename, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"); toast.success("Đã tạo file nhập liệu mẫu"); } }
  async function createBackup() { try { const response = await exportQuery.refetch(); if (!response.data) return; downloadBase64File(response.data.base64, response.data.filename, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"); await logMutation.mutateAsync({ actionType: "backup", status: "success", fileName: response.data.filename, notes: "Sao lưu logic danh sách nhân sự dưới định dạng Excel." }); toast.success("Đã tải bản sao lưu Excel và ghi nhận nhật ký"); } catch (error) { await logMutation.mutateAsync({ actionType: "backup", status: "failed", notes: error instanceof Error ? error.message : "Không thể tạo bản sao lưu" }); toast.error("Không thể tạo bản sao lưu"); } }
  async function executeImport(base64: string, fileName: string, mode: ImportMode, mappings?: Array<{ wardName: string; sourceTeamName: string; teamId: number }>) { const result = await importMutation.mutateAsync({ base64, teamMappings: mappings }); await logMutation.mutateAsync({ actionType: mode, status: "success", fileName, notes: `Đã ${mode === "import" ? "nhập" : "khôi phục"} ${result.imported} hồ sơ${result.errors.length ? `; có ${result.errors.length} dòng cần kiểm tra` : ""}.` }); await Promise.all([utils.personnel.list.invalidate(), utils.dashboard.stats.invalidate()]); if (result.errors.length) { downloadErrorReport(result.errors); toast.warning(`Đã nhập ${result.imported} hồ sơ; ${result.errors.length} dòng lỗi đã được xuất báo cáo.`); } else toast.success(`Đã ${mode === "import" ? "nhập" : "khôi phục"} ${result.imported} hồ sơ thành công.`); }
  async function handleImport(event: ChangeEvent<HTMLInputElement>, mode: ImportMode) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; if (!file.name.toLowerCase().endsWith(".xlsx")) { toast.error("Chỉ chấp nhận file có định dạng .xlsx"); return; } try { setProcessing(mode); const base64 = await readFileAsBase64(file); if (mode === "import") { const analysis = await analyzeMappingsMutation.mutateAsync({ base64 }); if (analysis.groups.length) { const groups = analysis.groups as BulkTeamMappingGroup[]; setPendingBulkImport({ base64, fileName: file.name, totalRows: analysis.totalRows, groups }); setTeamMappings(Object.fromEntries(groups.filter(group => group.suggestedTeamId).map(group => [bulkMappingKey(group), group.suggestedTeamId!] ))); toast.info(`Đã gom ${analysis.groups.length} nhóm Tổ chưa khớp để đối soát một lần.`); return; } } await executeImport(base64, file.name, mode); } catch (error) { await logMutation.mutateAsync({ actionType: mode, status: "failed", fileName: file.name, notes: error instanceof Error ? error.message : "Không thể xử lý dữ liệu" }); toast.error(error instanceof Error ? error.message : "Không thể xử lý file Excel"); } finally { setProcessing(null); } }
  async function confirmBulkImport() { if (!pendingBulkImport) return; try { setProcessing("import"); const mappings = pendingBulkImport.groups.map(group => ({ wardName: group.wardName, sourceTeamName: group.sourceTeamName, teamId: teamMappings[bulkMappingKey(group)] })).filter((mapping): mapping is { wardName: string; sourceTeamName: string; teamId: number } => Boolean(mapping.teamId)); await executeImport(pendingBulkImport.base64, pendingBulkImport.fileName, "import", mappings); setPendingBulkImport(null); setTeamMappings({}); } catch (error) { await logMutation.mutateAsync({ actionType: "import", status: "failed", fileName: pendingBulkImport.fileName, notes: error instanceof Error ? error.message : "Không thể xử lý dữ liệu" }); toast.error(error instanceof Error ? error.message : "Không thể nhập dữ liệu"); } finally { setProcessing(null); } }
  return <div className="mx-auto w-full max-w-[1400px] space-y-6"><PageHeader eyebrow="Quản trị dữ liệu" title="Backup & dữ liệu" description="Tạo tệp mẫu, nhập dữ liệu ban đầu, sao lưu logic theo Excel và theo dõi nhật ký thao tác." />
    <section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3"><ActionCard icon={FileSpreadsheet} color="navy" title="Xuất file nhập liệu mẫu" description="Tải mẫu mới; nhập đúng Xã/phường và Tên Tổ, không chỉnh sửa hàng tiêu đề." action="Tải file mẫu" onClick={downloadTemplate} loading={templateQuery.isFetching} /><ActionCard icon={Upload} color="red" title="Nhập dữ liệu từ Excel" description="Tự gom tên Tổ chưa khớp theo nhóm để đối soát một lần, rồi ghi hàng nghìn hồ sơ theo lô." action="Chọn file để nhập" onClick={() => importInputRef.current?.click()} loading={processing === "import"} /><ActionCard icon={ArchiveRestore} color="navy" title="Sao lưu dữ liệu" description="Xuất toàn bộ danh sách hiện có ra tệp Excel để lưu trữ và chia sẻ." action="Tạo bản sao lưu" onClick={createBackup} loading={exportQuery.isFetching || logMutation.isPending} /></section>
    {pendingBulkImport ? <BulkTeamMappingReview totalRows={pendingBulkImport.totalRows} groups={pendingBulkImport.groups} mappings={teamMappings} onChange={(key, teamId) => setTeamMappings(current => ({ ...current, [key]: teamId }))} onConfirm={() => void confirmBulkImport()} onCancel={() => { setPendingBulkImport(null); setTeamMappings({}); }} loading={processing === "import"} /> : null}
    <section className="grid gap-5 lg:grid-cols-[1.1fr_0.9fr]"><Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><RefreshCw className="h-4 w-4 text-[#b91d3b]" />Khôi phục từ tệp dữ liệu</CardTitle><CardDescription>Chức năng này nhập lại các hồ sơ từ tệp .xlsx đã được xuất hoặc tệp có đúng cấu trúc dữ liệu mẫu. Dữ liệu hợp lệ được bổ sung, không xóa dữ liệu hiện có.</CardDescription></CardHeader><CardContent><Button variant="outline" className="border-[#d6e3f3] bg-[#f8fbff] text-[#0b2f5b] hover:bg-[#eef5fd]" onClick={() => restoreInputRef.current?.click()} disabled={processing === "restore"}>{processing === "restore" ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <ArchiveRestore className="mr-2 h-4 w-4" />}Chọn file để khôi phục</Button><p className="mt-4 text-xs leading-5 text-slate-500">Để đảm bảo an toàn, hệ thống kiểm tra từng dòng và xuất báo cáo lỗi cho dữ liệu không hợp lệ.</p></CardContent></Card><Card className="border-[#f3d8dd] bg-[#fffafb] shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base text-[#95112e]"><CircleAlert className="h-4 w-4" />Lưu ý vận hành</CardTitle><CardDescription className="leading-6 text-slate-600">Bản sao lưu ở phiên bản web được cung cấp dưới dạng Excel. Cán bộ nên lưu tệp vào thư mục quản lý an toàn của đơn vị trước khi thực hiện các thao tác nhập hoặc điều chỉnh dữ liệu lớn.</CardDescription></CardHeader><CardContent><div className="rounded-xl bg-white p-3 text-sm text-slate-600 shadow-sm ring-1 ring-red-100">Khôi phục không ghi đè tự động các hồ sơ hiện có. Nếu cần thay đổi diện rộng, hãy sao lưu trước và kiểm tra báo cáo sau nhập.</div></CardContent></Card></section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-bold text-slate-950">Nhật ký Backup & dữ liệu</h2><p className="mt-0.5 text-sm text-slate-500">Theo dõi thao tác sao lưu, khôi phục, nhập và xuất dữ liệu.</p></div><History className="h-5 w-5 text-[#0b2f5b]" /></div><div className="overflow-x-auto"><Table><TableHeader className="bg-slate-50"><TableRow><TableHead className="pl-5">Thời điểm</TableHead><TableHead>Thao tác</TableHead><TableHead>Tệp dữ liệu</TableHead><TableHead>Người thực hiện</TableHead><TableHead>Trạng thái</TableHead><TableHead className="pr-5">Ghi chú</TableHead></TableRow></TableHeader><TableBody>{logsLoading ? <TableRow><TableCell colSpan={6} className="h-28 text-center text-sm text-slate-500">Đang tải nhật ký...</TableCell></TableRow> : null}{!logsLoading && logs.length === 0 ? <TableRow><TableCell colSpan={6} className="h-36 text-center text-sm text-slate-500">Chưa có thao tác dữ liệu nào được ghi nhận.</TableCell></TableRow> : null}{logs.map(log => <TableRow key={log.id} className="border-slate-100"><TableCell className="pl-5 text-sm text-slate-600">{new Intl.DateTimeFormat("vi-VN", { dateStyle: "short", timeStyle: "short" }).format(new Date(log.createdAt))}</TableCell><TableCell><Badge variant="secondary" className="capitalize">{actionLabel(log.actionType)}</Badge></TableCell><TableCell className="max-w-56 truncate text-sm text-slate-600">{log.fileName || "—"}</TableCell><TableCell className="text-sm text-slate-600">{log.actorName || "—"}</TableCell><TableCell>{log.status === "success" ? <Badge className="rounded-full bg-emerald-50 text-emerald-700 hover:bg-emerald-50"><CheckCircle2 className="mr-1 h-3 w-3" />Thành công</Badge> : <Badge className="rounded-full bg-red-50 text-red-700 hover:bg-red-50">Thất bại</Badge>}</TableCell><TableCell className="max-w-sm pr-5 text-sm text-slate-600">{log.notes || "—"}</TableCell></TableRow>)}</TableBody></Table></div></section><input ref={importInputRef} type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" className="hidden" onChange={event => handleImport(event, "import")} /><input ref={restoreInputRef} type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" className="hidden" onChange={event => handleImport(event, "restore")} /></div>;
}

function ActionCard({ icon: Icon, color, title, description, action, onClick, loading }: { icon: typeof FileSpreadsheet; color: "navy" | "red"; title: string; description: string; action: string; onClick: () => void; loading: boolean }) { const colors = color === "red" ? "bg-red-50 text-[#b91d3b]" : "bg-[#edf4fc] text-[#0b2f5b]"; return <Card className="border-slate-200 shadow-sm"><CardHeader><span className={`grid h-10 w-10 place-items-center rounded-xl ${colors}`}><Icon className="h-5 w-5" /></span><CardTitle className="mt-3 text-base">{title}</CardTitle><CardDescription className="min-h-10 leading-5">{description}</CardDescription></CardHeader><CardContent><Button variant="outline" className="w-full border-slate-200" onClick={onClick} disabled={loading}>{loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Download className="mr-2 h-4 w-4" />}{action}</Button></CardContent></Card>; }
function actionLabel(value: string) { return ({ backup: "Sao lưu", restore: "Khôi phục", import: "Nhập dữ liệu", export: "Xuất dữ liệu" } as Record<string, string>)[value] || value; }
function getImportErrorGuidance(message: string) {
  if (message.includes("CCCD phải có 9 hoặc 12 chữ số")) return "Xóa dấu cách, dấu chấm hoặc gạch nối; nhập 9 hoặc 12 chữ số. Nếu CCCD bắt đầu bằng 0, đặt ô CCCD ở dạng Văn bản hoặc gõ dấu nháy đơn (') trước số để giữ số 0. Nếu chưa có CCCD, để trống ô.";
  if (message.includes("Tổ gần khớp tại Xã/phường này")) return "Chọn lại Tên Tổ bằng dropdown theo một trong các Tổ gần khớp được nêu trong cột Lỗi; không gõ tay tên Tổ.";
  if (message.includes("Không tìm thấy Tổ") && message.includes("thuộc Xã/phường")) return "Tải lại file mẫu mới, chọn lại Xã/Phường rồi chọn Tên Tổ bằng dropdown. Không gõ tay tên Tổ.";
  if (message.includes("Thiếu Tổ")) return "Chọn Xã/Phường trước, sau đó chọn Tên Tổ bằng dropdown. Không để trống cột TenTo.";
  if (message.includes("Không tìm thấy Xã/phường")) return "Tải lại file mẫu mới và chọn Xã/Phường từ dropdown; không gõ tay tên xã/phường.";
  if (message.includes("Ngày sinh không hợp lệ")) return "Nhập ngày theo dạng dd/mm/yyyy hoặc chọn định dạng Ngày trong Excel.";
  return "Kiểm tra lại nội dung cột được nêu trong lỗi, sau đó nhập lại file.";
}

function csvCell(value: string | number) { return `"${String(value).replaceAll('"', '""')}"`; }

function downloadErrorReport(errors: Array<{ row: number; message: string }>) { const csv = `\uFEFFDòng,Lỗi,Hướng xử lý\n${errors.map(item => `${csvCell(item.row)},${csvCell(item.message)},${csvCell(getImportErrorGuidance(item.message))}`).join("\n")}`; const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "bao-cao-loi-nhap-du-lieu.csv"; anchor.click(); URL.revokeObjectURL(url); }
