import { PageHeader } from "@/components/PageHeader";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { PersonnelAchievementsPanel } from "@/components/PersonnelAchievementsPanel";
import { useAuth } from "@/_core/hooks/useAuth";
import { downloadBase64File, readFileAsBase64 } from "@/lib/download";
import { trpc } from "@/lib/trpc";
import { hasLeaderDelegatedPermission } from "@shared/leader-permissions";
import { Award, ChevronDown, FileText, ImagePlus, Loader2, Pencil, Plus, Search, Trash2, Upload, UserRound, X, FileUp, ExternalLink, MessageSquareWarning, GraduationCap } from "lucide-react";
import React, { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

type Gender = "male" | "female" | "other" | null;
type Classification = string;
type StatusFilter = "all" | "active" | "inactive";
type AgeGroupFilter = "all" | "under_70" | "from_70" | "unknown";
type FormState = {
  fullName: string; dateOfBirth: string; gender: Gender; citizenId: string; phone: string; address: string; ethnicity: string; religion: string; educationLevel: string; position: string; unitId: string; joinedFormerForceAt: string; joinedAt: string; leftFormerForceAt: string; leftAt: string; policyResult: string; certificateNumber: string; commendation: string; classification: Classification; classificationDecision: string; notes: string;
};

const emptyForm: FormState = { fullName: "", dateOfBirth: "", gender: null, citizenId: "", phone: "", address: "", ethnicity: "", religion: "", educationLevel: "", position: "", unitId: "", joinedFormerForceAt: "", joinedAt: "", leftFormerForceAt: "", leftAt: "", policyResult: "", certificateNumber: "", commendation: "", classification: "", classificationDecision: "", notes: "" };

function isoInput(value: Date | string | null | undefined) {
  if (!value) return "";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "" : date.toISOString().slice(0, 10);
}

function toDate(value: string) { return value ? new Date(`${value}T00:00:00.000Z`) : null; }
function nullable(value: string) { return value.trim() || null; }
const classificationLabels: Record<string, string> = { excellent: "Hoàn thành xuất sắc nhiệm vụ", good: "Hoàn thành tốt nhiệm vụ", completed: "Hoàn thành nhiệm vụ", not_completed: "Không hoàn thành nhiệm vụ" };
function classificationValue(value: unknown): Classification { return typeof value === "string" ? classificationLabels[value] ?? value : ""; }
function classificationCode(value: string): "excellent" | "good" | "completed" | "not_completed" | null { const text = value.trim().toLocaleLowerCase("vi"); if (text === "excellent" || text.includes("hoàn thành xuất sắc")) return "excellent"; if (text === "good" || text.includes("hoàn thành tốt")) return "good"; if (text === "not_completed" || text.includes("không hoàn thành")) return "not_completed"; if (text === "completed" || text.includes("hoàn thành nhiệm vụ")) return "completed"; return null; }
function toForm(record: any): FormState {
  return { fullName: record.fullName ?? "", dateOfBirth: isoInput(record.dateOfBirth), gender: record.gender ?? null, citizenId: record.citizenId ?? "", phone: record.phone ?? "", address: record.address || record.village || "", ethnicity: record.ethnicity ?? "", religion: record.religion ?? "", educationLevel: record.educationLevel ?? "", position: record.position ?? "", unitId: record.unitId ? String(record.unitId) : "", joinedFormerForceAt: isoInput(record.joinedFormerForceAt), joinedAt: isoInput(record.joinedAt), leftFormerForceAt: isoInput(record.leftFormerForceAt), leftAt: isoInput(record.leftAt), policyResult: record.policyResult ?? "", certificateNumber: record.certificateNumber ?? "", commendation: record.commendation ?? "", classification: classificationValue(record.classification), classificationDecision: record.classificationDecision ?? "", notes: record.notes ?? "" };
}

export default function PersonnelPage() {
  const { user } = useAuth();
  const isAdmin = user?.role === "admin" || (user?.role === "leader" && hasLeaderDelegatedPermission(user.adminPermissions, "deletePersonnel"));
  const canFilterByWard = user?.role === "admin" || user?.role === "leader";
  const canExport = Boolean(user);
  const canEdit = user?.role === "admin" || (user?.role === "leader" && hasLeaderDelegatedPermission(user.adminPermissions, "managePersonnel")) || (user?.role === "user" && user.canEditPersonnel);
  const [keyword, setKeyword] = useState("");
  const [position, setPosition] = useState("");
  const [unitId, setUnitId] = useState("all");
  const [wardIds, setWardIds] = useState<number[]>([]);
  const [wardSearch, setWardSearch] = useState("");
  const [status, setStatus] = useState<StatusFilter>("all");
  const [ageGroup, setAgeGroup] = useState<AgeGroupFilter>("all");
  const [filters, setFilters] = useState({ keyword: "", position: "", unitId: undefined as number | undefined, wardIds: undefined as number[] | undefined, status: undefined as "active" | "inactive" | undefined, ageGroup: undefined as "under_70" | "from_70" | "unknown" | undefined });
  const [selectedIds, setSelectedIds] = useState<number[]>([]);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [deletionTarget, setDeletionTarget] = useState<{ id: number; name: string } | null>(null);

  const { data: units = [] } = trpc.units.list.useQuery();
  const teams = units.filter(unit => unit.unitType === "team");
  const wards = units.filter(unit => unit.unitType === "ward");
  const visibleTeams = wardIds.length ? teams.filter(unit => wardIds.includes(unit.parentId ?? 0)) : teams;
  const filteredWards = wards.filter(unit => unit.name.toLocaleLowerCase("vi").includes(wardSearch.trim().toLocaleLowerCase("vi")));
  const wardFilterLabel = wardIds.length === 0 ? "Tất cả xã/phường" : wardIds.length === 1 ? wards.find(unit => unit.id === wardIds[0])?.name ?? "1 xã/phường" : `${wardIds.length} xã/phường đã chọn`;
  const { data: rows = [], isLoading } = trpc.personnel.list.useQuery(filters);
  const detailQuery = trpc.personnel.detail.useQuery({ id: editingId ?? 1 }, { enabled: dialogOpen && editingId !== null });
  const utils = trpc.useUtils();
  const createMutation = trpc.personnel.create.useMutation({ onSuccess: async () => { await utils.personnel.list.invalidate(); toast.success("Đã thêm hồ sơ nhân sự"); closeDialog(); } });
  const updateMutation = trpc.personnel.update.useMutation({ onSuccess: async () => { await utils.personnel.list.invalidate(); await utils.personnel.detail.invalidate(); toast.success("Đã cập nhật hồ sơ nhân sự"); closeDialog(); } });
  const removeMutation = trpc.personnel.remove.useMutation({ onSuccess: async () => { setSelectedIds([]); await utils.personnel.list.invalidate(); toast.success("Đã xóa hồ sơ được chọn"); } });
  const deleteRequestMutation = trpc.deletionRequests.create.useMutation();
  const uploadEvidenceMutation = trpc.deletionRequests.uploadEvidence.useMutation();
  const { data: editAccessRequest } = trpc.editAccess.mine.useQuery(undefined, { enabled: user?.role === "user" });
  const requestEditAccessMutation = trpc.editAccess.request.useMutation({ onSuccess: async () => { await utils.editAccess.mine.invalidate(); toast.success("Đã gửi yêu cầu mở quyền chỉnh sửa đến Admin"); } });
  const exportQuery = trpc.excel.exportPersonnel.useQuery(filters, { enabled: false });

  const selectedAll = rows.length > 0 && rows.every(row => selectedIds.includes(row.id));
  const activeFiltersCount = Number(Boolean(filters.keyword)) + Number(Boolean(filters.position)) + Number(Boolean(filters.unitId)) + Number(Boolean(filters.wardIds?.length)) + Number(Boolean(filters.status)) + Number(Boolean(filters.ageGroup));

  function applyFilters() { setFilters({ keyword: keyword.trim(), position: position.trim(), unitId: unitId === "all" ? undefined : Number(unitId), wardIds: canFilterByWard && wardIds.length ? wardIds : undefined, status: status === "all" ? undefined : status, ageGroup: ageGroup === "all" ? undefined : ageGroup }); }
  function resetFilters() { setKeyword(""); setPosition(""); setUnitId("all"); setWardIds([]); setWardSearch(""); setStatus("all"); setAgeGroup("all"); setFilters({ keyword: "", position: "", unitId: undefined, wardIds: undefined, status: undefined, ageGroup: undefined }); }
  function toggleWard(wardId: number) { setWardIds(current => current.includes(wardId) ? current.filter(id => id !== wardId) : [...current, wardId]); setUnitId("all"); }
  function toggleRow(id: number) { setSelectedIds(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]); }
  function closeDialog() { setDialogOpen(false); setEditingId(null); }
  function startCreate() { setEditingId(null); setDialogOpen(true); }
  function startEdit(id: number) { setEditingId(id); setDialogOpen(true); }
  async function exportFile() { const result = await exportQuery.refetch(); if (result.data) { downloadBase64File(result.data.base64, result.data.filename, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"); toast.success("Đã tạo tệp Excel danh sách nhân sự"); } }
  function requestEditAccess() { const reason = window.prompt("Nêu lý do cần chỉnh sửa dữ liệu (ít nhất 10 ký tự):"); if (reason === null) return; if (reason.trim().length < 10) { toast.error("Vui lòng nêu lý do từ 10 ký tự trở lên"); return; } requestEditAccessMutation.mutate({ reason: reason.trim() }); }

  return (
    <div className="mx-auto w-full max-w-[1500px] space-y-6">
      <PageHeader eyebrow="Hồ sơ lực lượng" title="Danh sách thành viên" description={user?.role === "user" ? (canEdit ? "Quyền chỉnh sửa đang được Admin mở cho xã/phường được phân công; thao tác xóa do Admin thực hiện." : editAccessRequest?.status === "pending" ? "Chế độ chỉ xem và tải dữ liệu. Yêu cầu mở quyền chỉnh sửa đang chờ Admin xử lý." : "Chế độ chỉ xem và tải dữ liệu thuộc xã/phường được phân công. Muốn chỉnh sửa, hãy gửi yêu cầu để Admin phê duyệt.") : "Tra cứu, cập nhật và lưu trữ hồ sơ lực lượng tham gia bảo vệ ANTT ở cơ sở."} actions={<>{canExport ? <Button variant="outline" className="border-slate-300 bg-white" onClick={exportFile} disabled={exportQuery.isFetching}><FileUp className="mr-2 h-4 w-4" />Xuất Excel</Button> : null}{user?.role === "user" && !canEdit ? <Button variant="outline" className="border-[#d6e3f3] text-[#0b2f5b] hover:bg-[#edf4fc]" onClick={requestEditAccess} disabled={editAccessRequest?.status === "pending" || requestEditAccessMutation.isPending}><MessageSquareWarning className="mr-2 h-4 w-4" />{editAccessRequest?.status === "pending" ? "Đang chờ phê duyệt" : "Yêu cầu quyền chỉnh sửa"}</Button> : null}{canEdit ? <Button className="bg-[#b91d3b] hover:bg-[#98142f]" onClick={startCreate}><Plus className="mr-2 h-4 w-4" />Thêm thành viên</Button> : null}</>} />

      <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5">
        <div className="mb-4 flex flex-col gap-1 border-b border-slate-100 pb-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-slate-800">Bộ lọc nâng cao</p><p className="mt-0.5 text-xs text-slate-500">Kết hợp tên, chức vụ, đơn vị, trạng thái và nhóm tuổi để thu hẹp kết quả.</p></div><Badge variant="secondary" className="w-fit rounded-full bg-[#edf3fb] text-[#0b2f5b]">{activeFiltersCount} tiêu chí đang áp dụng</Badge></div>
        <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
          <div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input value={keyword} onChange={event => setKeyword(event.target.value)} onKeyDown={event => event.key === "Enter" && applyFilters()} placeholder="Họ tên, CCCD hoặc số điện thoại" className="h-11 border-slate-200 pl-9" /></div>
          <Input value={position} onChange={event => setPosition(event.target.value)} onKeyDown={event => event.key === "Enter" && applyFilters()} placeholder="Chức vụ" className="h-11 border-slate-200" />
          {canFilterByWard ? <Popover><PopoverTrigger asChild><Button type="button" variant="outline" className="h-11 justify-between border-slate-200 bg-white font-normal text-slate-700 hover:bg-slate-50"><span className="truncate">{wardFilterLabel}</span><ChevronDown className="ml-2 h-4 w-4 shrink-0 text-slate-500" /></Button></PopoverTrigger><PopoverContent align="start" className="w-[min(22rem,calc(100vw-2rem))] p-3"><div className="mb-2 flex items-center justify-between gap-3"><p className="text-sm font-semibold text-slate-800">Chọn xã/phường</p><div className="flex gap-1"><Button type="button" variant="ghost" size="sm" className="h-7 px-2 text-xs" onClick={() => { setWardIds(wards.map(unit => unit.id)); setUnitId("all"); }}>Chọn tất cả</Button><Button type="button" variant="ghost" size="sm" className="h-7 px-2 text-xs" onClick={() => { setWardIds([]); setUnitId("all"); }}>Bỏ chọn</Button></div></div><Input value={wardSearch} onChange={event => setWardSearch(event.target.value)} placeholder="Tìm xã/phường..." className="mb-2 h-9" /><div className="max-h-56 space-y-1 overflow-y-auto pr-1">{filteredWards.map(unit => <label key={unit.id} className="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 text-sm text-slate-700 hover:bg-slate-50"><Checkbox checked={wardIds.includes(unit.id)} onCheckedChange={() => toggleWard(unit.id)} aria-label={`Chọn ${unit.name}`} /><span className="min-w-0 truncate">{unit.name}</span></label>)}{filteredWards.length === 0 ? <p className="px-2 py-3 text-sm text-slate-500">Không tìm thấy xã/phường phù hợp.</p> : null}</div></PopoverContent></Popover> : null}
          <Select value={unitId} onValueChange={setUnitId}><SelectTrigger className="h-11 border-slate-200"><SelectValue placeholder="Tổ bảo vệ an ninh, trật tự" /></SelectTrigger><SelectContent><SelectItem value="all">Tất cả Tổ bảo vệ an ninh, trật tự</SelectItem>{visibleTeams.map(unit => <SelectItem key={unit.id} value={String(unit.id)}>{unit.name}</SelectItem>)}</SelectContent></Select>
          <Select value={status} onValueChange={value => setStatus(value as StatusFilter)}><SelectTrigger className="h-11 border-slate-200"><SelectValue placeholder="Trạng thái" /></SelectTrigger><SelectContent><SelectItem value="all">Tất cả trạng thái</SelectItem><SelectItem value="active">Đang tham gia</SelectItem><SelectItem value="inactive">Thôi tham gia</SelectItem></SelectContent></Select>
          <Select value={ageGroup} onValueChange={value => setAgeGroup(value as AgeGroupFilter)}><SelectTrigger className="h-11 border-slate-200"><SelectValue placeholder="Nhóm tuổi" /></SelectTrigger><SelectContent><SelectItem value="all">Tất cả nhóm tuổi</SelectItem><SelectItem value="under_70">Dưới 70 tuổi</SelectItem><SelectItem value="from_70">Từ 70 tuổi trở lên</SelectItem><SelectItem value="unknown">Chưa có ngày sinh</SelectItem></SelectContent></Select>
          <Button className="h-11 bg-[#0b2f5b] hover:bg-[#08274c]" onClick={applyFilters}><Search className="mr-2 h-4 w-4" />Tra cứu</Button>
        </div>
        <div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-4"><p className="text-sm text-slate-500">{activeFiltersCount ? `Đang áp dụng ${activeFiltersCount} tiêu chí tìm kiếm.` : "Nhập tiêu chí và bấm Tra cứu để lọc danh sách."}</p><div className="flex gap-2"><Button variant="ghost" size="sm" className="text-slate-600" onClick={resetFilters}><X className="mr-1.5 h-3.5 w-3.5" />Đặt lại</Button>{isAdmin && selectedIds.length ? <Button variant="outline" size="sm" className="border-red-200 text-red-700 hover:bg-red-50 hover:text-red-800" disabled={removeMutation.isPending} onClick={() => { if (window.confirm(`Xóa ${selectedIds.length} hồ sơ đã chọn? Thao tác này không thể hoàn tác.`)) removeMutation.mutate({ ids: selectedIds }); }}><Trash2 className="mr-1.5 h-3.5 w-3.5" />Xóa ({selectedIds.length})</Button> : null}</div></div>
      </section>

      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-bold text-slate-950">Danh sách hồ sơ</h2><p className="mt-0.5 text-sm text-slate-500">{isLoading ? "Đang tải dữ liệu..." : `${rows.length} hồ sơ phù hợp`}</p></div><Badge variant="secondary" className="rounded-full bg-[#edf3fb] text-[#0b2f5b]">Bấm đúp vào dòng để xem hồ sơ</Badge></div>
        <div className="overflow-x-auto"><Table><TableHeader className="bg-slate-50"><TableRow className="hover:bg-slate-50"><TableHead className="w-12 px-5">{isAdmin ? <Checkbox checked={selectedAll} onCheckedChange={() => setSelectedIds(selectedAll ? [] : rows.map(row => row.id))} aria-label="Chọn tất cả" /> : null}</TableHead><TableHead>Họ và tên</TableHead><TableHead>Đơn vị</TableHead><TableHead>Số điện thoại</TableHead><TableHead>Trạng thái</TableHead></TableRow></TableHeader><TableBody>
          {isLoading ? <TableRow><TableCell colSpan={isAdmin ? 5 : 4} className="h-40 text-center text-sm text-slate-500"><Loader2 className="mx-auto mb-2 h-5 w-5 animate-spin text-[#0b2f5b]" />Đang tải danh sách...</TableCell></TableRow> : null}
          {!isLoading && rows.length === 0 ? <TableRow><TableCell colSpan={isAdmin ? 5 : 4} className="h-48 text-center"><UserRound className="mx-auto mb-3 h-8 w-8 text-slate-300" /><p className="font-medium text-slate-700">Chưa có hồ sơ phù hợp</p><p className="mt-1 text-sm text-slate-500">{activeFiltersCount ? "Hãy điều chỉnh bộ lọc hoặc đặt lại tìm kiếm." : canEdit ? "Bạn có thể thêm hồ sơ mới trong phạm vi được phân công." : "Chế độ Lãnh đạo chỉ cho phép xem và tra cứu."}</p></TableCell></TableRow> : null}
          {!isLoading && rows.map(row => <TableRow key={row.id} onDoubleClick={() => startEdit(row.id)} className="cursor-pointer border-slate-100 hover:bg-[#f8fbff]"><TableCell className="px-5">{isAdmin ? <Checkbox checked={selectedIds.includes(row.id)} onCheckedChange={() => toggleRow(row.id)} onClick={event => event.stopPropagation()} aria-label={`Chọn ${row.fullName}`} /> : null}</TableCell><TableCell className="font-semibold text-slate-900">{row.fullName}</TableCell><TableCell className="text-slate-700">{row.unitName || "Chưa phân loại"}</TableCell><TableCell className="text-slate-700">{row.phone || "—"}</TableCell><TableCell><StatusBadge status={row.status} /></TableCell></TableRow>)}
        </TableBody></Table></div>
      </section>

      <PersonnelDialog open={dialogOpen} onOpenChange={open => { if (!open) closeDialog(); else setDialogOpen(true); }} editingId={editingId} initialRecord={detailQuery.data?.personnel} files={detailQuery.data?.files ?? []} commendations={detailQuery.data?.commendations ?? []} trainings={detailQuery.data?.trainings ?? []} units={teams} canEdit={canEdit} canDeleteFiles={isAdmin} canRequestDeletion={user?.role === "user"} onRequestDeletion={() => { if (editingId && detailQuery.data?.personnel) { closeDialog(); setDeletionTarget({ id: editingId, name: detailQuery.data.personnel.fullName }); } }} onSubmit={async form => { if (!form.unitId) { toast.error("Vui lòng chọn Tổ bảo vệ an ninh, trật tự cho hồ sơ nhân sự"); return; } const payload = toPayload(form); if (editingId) await updateMutation.mutateAsync({ id: editingId, payload }); else await createMutation.mutateAsync(payload); }} pending={createMutation.isPending || updateMutation.isPending} onFileUploaded={() => { void utils.personnel.detail.invalidate(); void utils.personnel.list.invalidate(); }} />
      <DeletionRequestDialog target={deletionTarget} open={Boolean(deletionTarget)} pending={deleteRequestMutation.isPending || uploadEvidenceMutation.isPending} onOpenChange={open => { if (!open) setDeletionTarget(null); }} onSubmit={async (reason, evidenceFiles) => { if (!deletionTarget) return; try { const requestId = await deleteRequestMutation.mutateAsync({ personnelId: deletionTarget.id, reason }); for (const file of evidenceFiles) await uploadEvidenceMutation.mutateAsync({ deletionRequestId: requestId, originalName: file.name, mimeType: file.type || "application/octet-stream", base64: await readFileAsBase64(file) }); await utils.deletionRequests.mine.invalidate(); toast.success(evidenceFiles.length ? `Đã gửi yêu cầu xóa kèm ${evidenceFiles.length} tệp minh chứng` : "Đã gửi yêu cầu xóa để Admin xem xét"); setDeletionTarget(null); } catch (error) { toast.error(error instanceof Error ? error.message : "Không thể gửi yêu cầu xóa hoặc tải tệp minh chứng"); } }} />
    </div>
  );
}

function StatusBadge({ status }: { status: "active" | "inactive" }) { return <Badge className={status === "active" ? "rounded-full bg-emerald-50 text-emerald-700 hover:bg-emerald-50" : "rounded-full bg-red-50 text-red-700 hover:bg-red-50"}>{status === "active" ? "Đang tham gia" : "Thôi tham gia"}</Badge>; }

function toPayload(form: FormState) {
  return { fullName: form.fullName.trim(), dateOfBirth: toDate(form.dateOfBirth), gender: form.gender, citizenId: nullable(form.citizenId), phone: nullable(form.phone), address: nullable(form.address), ethnicity: nullable(form.ethnicity), religion: nullable(form.religion), educationLevel: nullable(form.educationLevel), position: nullable(form.position), unitId: Number(form.unitId), joinedFormerForceAt: toDate(form.joinedFormerForceAt), joinedAt: toDate(form.joinedAt), leftFormerForceAt: toDate(form.leftFormerForceAt), leftAt: toDate(form.leftAt), policyResult: nullable(form.policyResult), certificateNumber: nullable(form.certificateNumber), commendation: nullable(form.commendation), classification: classificationCode(form.classification), classificationDecision: nullable(form.classificationDecision), notes: nullable(form.notes) };
}

function PersonnelDialog({ open, onOpenChange, editingId, initialRecord, files, commendations, trainings, units, canEdit, canDeleteFiles, canRequestDeletion, onRequestDeletion, onSubmit, pending, onFileUploaded }: { open: boolean; onOpenChange: (open: boolean) => void; editingId: number | null; initialRecord: any; files: any[]; commendations: any[]; trainings: any[]; units: any[]; canEdit: boolean; canDeleteFiles: boolean; canRequestDeletion: boolean; onRequestDeletion: () => void; onSubmit: (form: FormState) => Promise<void>; pending: boolean; onFileUploaded: () => void; }) {
  const [form, setForm] = useState<FormState>(emptyForm);
  const utils = trpc.useUtils();
  const uploadMutation = trpc.personnel.uploadFile.useMutation({ onSuccess: () => { onFileUploaded(); toast.success("Đã tải tệp hồ sơ lên"); } });
  const removeFileMutation = trpc.personnel.removeFile.useMutation({ onSuccess: async () => { await utils.personnel.detail.invalidate(); toast.success("Đã gỡ tệp khỏi hồ sơ"); } });
  useEffect(() => { if (!open) return; setForm(initialRecord ? toForm(initialRecord) : emptyForm); const handler = (event: Event) => setForm(current => ({ ...current, classification: (event as CustomEvent<string>).detail })); window.addEventListener("personnel-classification-change", handler); return () => window.removeEventListener("personnel-classification-change", handler); }, [open, initialRecord, editingId]);
  const portrait = useMemo(() => files.find(file => file.fileType === "portrait"), [files]);
  function change(field: keyof FormState, value: string | Gender) { setForm(current => ({ ...current, [field]: value })); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!canEdit) return; await onSubmit(form); }
  async function upload(event: ChangeEvent<HTMLInputElement>, fileType: "portrait" | "recruitment_decision" | "resignation_decision" | "other") { const file = event.target.files?.[0]; event.target.value = ""; if (!file || !editingId) return; try { const base64 = await readFileAsBase64(file); await uploadMutation.mutateAsync({ personnelId: editingId, fileType, originalName: file.name, mimeType: file.type || "application/octet-stream", base64 }); } catch (error) { toast.error(error instanceof Error ? error.message : "Không thể tải tệp lên"); } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] max-w-5xl overflow-y-auto p-0"><form onSubmit={submit}><DialogHeader className="sticky top-0 z-10 border-b border-slate-100 bg-white px-6 py-5"><DialogTitle className="text-xl text-slate-950">{editingId ? "Hồ sơ thành viên" : "Thêm thành viên mới"}</DialogTitle><DialogDescription>{canEdit ? "Cập nhật thông tin hồ sơ và tệp lưu trữ. Trạng thái sẽ tự chuyển thành Thôi tham gia khi có ngày thôi tham gia." : "Chế độ chỉ xem: quyền chỉnh sửa chỉ được mở khi Admin phê duyệt."}</DialogDescription></DialogHeader><div className="space-y-7 px-6 py-6">
    <section className="grid gap-6 lg:grid-cols-[160px_1fr]"><div className="flex flex-col items-center gap-3"><Avatar className="h-28 w-28 border-4 border-slate-100"><AvatarImage src={portrait?.storageUrl} className="object-cover" /><AvatarFallback className="bg-[#edf4fc] text-3xl font-bold text-[#0b2f5b]">{form.fullName.trim().split(" ").slice(-1)[0]?.[0] || "?"}</AvatarFallback></Avatar>{canEdit && editingId ? <label className="inline-flex cursor-pointer items-center gap-1.5 text-xs font-semibold text-[#0b2f5b] hover:text-[#b91d3b]"><ImagePlus className="h-3.5 w-3.5" />Cập nhật ảnh<input type="file" accept="image/*" className="hidden" onChange={event => upload(event, "portrait")} /></label> : <p className="text-center text-xs leading-5 text-slate-400">Lưu hồ sơ trước để cập nhật ảnh thẻ.</p>}</div><div><SectionTitle title="Thông tin định danh" /><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Họ và tên" required><Input disabled={!canEdit} value={form.fullName} onChange={event => change("fullName", event.target.value)} required /></Field><Field label="Ngày sinh"><Input disabled={!canEdit} type="date" value={form.dateOfBirth} onChange={event => change("dateOfBirth", event.target.value)} /></Field><Field label="Giới tính"><Select disabled={!canEdit} value={form.gender ?? "none"} onValueChange={value => change("gender", value === "none" ? null : value as Gender)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Chưa cập nhật</SelectItem><SelectItem value="male">Nam</SelectItem><SelectItem value="female">Nữ</SelectItem><SelectItem value="other">Khác</SelectItem></SelectContent></Select></Field><Field label="Số CCCD"><Input disabled={!canEdit} value={form.citizenId} onChange={event => change("citizenId", event.target.value)} inputMode="numeric" /></Field><Field label="Số điện thoại"><Input disabled={!canEdit} value={form.phone} onChange={event => change("phone", event.target.value)} /></Field><Field label="Dân tộc"><Input disabled={!canEdit} value={form.ethnicity} onChange={event => change("ethnicity", event.target.value)} /></Field><Field label="Tôn giáo"><Input disabled={!canEdit} value={form.religion} onChange={event => change("religion", event.target.value)} /></Field><Field label="Trình độ"><Input disabled={!canEdit} value={form.educationLevel} onChange={event => change("educationLevel", event.target.value)} /></Field><Field label="Địa chỉ" className="sm:col-span-2 lg:col-span-3"><Textarea disabled={!canEdit} value={form.address} onChange={event => change("address", event.target.value)} placeholder="Ví dụ: Thôn/Tổ dân phố…, Xã/Phường…, Tỉnh…" rows={2} /></Field></div></div></section>
    <section><SectionTitle title="Thông tin tham gia lực lượng" /><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Chức vụ"><Input disabled={!canEdit} value={form.position} onChange={event => change("position", event.target.value)} /></Field><Field label="Tổ bảo vệ an ninh, trật tự" required><Select disabled={!canEdit} value={form.unitId || "unassigned"} onValueChange={value => change("unitId", value === "unassigned" ? "" : value)}><SelectTrigger><SelectValue placeholder="Chọn Tổ bảo vệ an ninh, trật tự" /></SelectTrigger><SelectContent>{!form.unitId ? <SelectItem value="unassigned" disabled>Chọn Tổ bảo vệ an ninh, trật tự để tính quân số</SelectItem> : null}{units.map(unit => <SelectItem key={unit.id} value={String(unit.id)}>{unit.name}</SelectItem>)}</SelectContent></Select><p className="mt-1 text-xs text-slate-500">Hồ sơ được tính quân số theo Tổ bảo vệ an ninh, trật tự đã chọn.</p></Field><Field label="Số GCN sử dụng CCHT"><Input disabled={!canEdit} value={form.certificateNumber} onChange={event => change("certificateNumber", event.target.value)} /></Field><Field label="Ngày tham gia CAXBCT/BVDP"><Input disabled={!canEdit} type="date" value={form.joinedFormerForceAt} onChange={event => change("joinedFormerForceAt", event.target.value)} /></Field><Field label="Ngày tham gia LLTGBVANTT"><Input disabled={!canEdit} type="date" value={form.joinedAt} onChange={event => change("joinedAt", event.target.value)} /></Field><Field label="Ngày thôi CAXBCT/BVDP"><Input disabled={!canEdit} type="date" value={form.leftFormerForceAt} onChange={event => change("leftFormerForceAt", event.target.value)} /></Field><Field label="Ngày thôi tham gia LLTGBVANTT"><Input disabled={!canEdit} type="date" value={form.leftAt} onChange={event => change("leftAt", event.target.value)} /><p className="mt-1 text-xs text-red-700">Có ngày thôi tham gia sẽ chuyển trạng thái tự động.</p></Field><Field label="Kết quả chính sách" className="sm:col-span-2"><Input disabled={!canEdit} value={form.policyResult} onChange={event => change("policyResult", event.target.value)} /></Field><Field label="Khen thưởng"><Input disabled={!canEdit} value={form.commendation} onChange={event => change("commendation", event.target.value)} /></Field><Field label="Mức xếp loại"><Input disabled={!canEdit} value={form.classification} onChange={event => change("classification", event.target.value)} /></Field><Field label="Quyết định xếp loại"><Input disabled={!canEdit} value={form.classificationDecision} onChange={event => change("classificationDecision", event.target.value)} /></Field><Field label="Ghi chú" className="sm:col-span-2 lg:col-span-3"><Textarea disabled={!canEdit} value={form.notes} onChange={event => change("notes", event.target.value)} rows={2} /></Field></div></section>
    {editingId ? <><section><SectionTitle title="Quyết định và tệp lưu trữ hồ sơ" /><div className="mt-4 grid gap-3 sm:grid-cols-3"><FileUploadCard title="Quyết định tham gia lực lượng" description="Ảnh hoặc PDF" accept="image/*,application/pdf" disabled={!canEdit || uploadMutation.isPending} onChange={event => upload(event, "recruitment_decision")} /><FileUploadCard title="Quyết định cho thôi tham gia" description="Ảnh hoặc PDF" accept="image/*,application/pdf" disabled={!canEdit || uploadMutation.isPending} onChange={event => upload(event, "resignation_decision")} /><FileUploadCard title="Tệp hồ sơ khác" description="Ảnh hoặc PDF" accept="image/*,application/pdf" disabled={!canEdit || uploadMutation.isPending} onChange={event => upload(event, "other")} /></div>{files.filter(file => file.fileType !== "portrait").length ? <div className="mt-4 space-y-2">{files.filter(file => file.fileType !== "portrait").map(file => <div className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 px-3 py-2.5" key={file.id}><div className="flex min-w-0 items-center gap-2"><FileText className="h-4 w-4 shrink-0 text-[#b91d3b]" /><span className="truncate text-sm font-medium text-slate-700">{file.originalName}</span><Badge variant="secondary" className="hidden text-[10px] sm:inline-flex">{file.fileType === "recruitment_decision" ? "Quyết định tham gia" : file.fileType === "resignation_decision" ? "Quyết định cho thôi tham gia" : "Khác"}</Badge></div><div className="flex shrink-0 gap-1"><a className="inline-flex h-8 w-8 items-center justify-center rounded-lg text-[#0b2f5b] hover:bg-slate-100" href={file.storageUrl} target="_blank" rel="noreferrer" aria-label={`Mở ${file.originalName}`}><ExternalLink className="h-4 w-4" /></a>{canDeleteFiles ? <Button type="button" variant="ghost" size="icon" className="h-8 w-8 text-red-700 hover:bg-red-50 hover:text-red-800" onClick={() => { if (window.confirm("Gỡ tệp này khỏi hồ sơ?")) removeFileMutation.mutate({ id: file.id }); }}><Trash2 className="h-4 w-4" /></Button> : null}</div></div>)}</div> : <p className="mt-4 rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-500">Chưa có quyết định hoặc tệp đính kèm.</p>}</section><PersonnelAchievementsPanel personnelId={editingId} commendations={commendations} trainings={trainings} canEdit={canEdit} onChanged={onFileUploaded} /></> : null}
  </div><DialogFooter className="sticky bottom-0 border-t border-slate-100 bg-white px-6 py-4"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Đóng</Button>{canRequestDeletion && editingId ? <Button type="button" variant="outline" className="border-red-200 text-red-700 hover:bg-red-50 hover:text-red-800" onClick={onRequestDeletion}><MessageSquareWarning className="mr-2 h-4 w-4" />Yêu cầu xóa</Button> : null}{canEdit ? <Button type="submit" className="bg-[#0b2f5b] hover:bg-[#08274c]" disabled={pending}>{pending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}Lưu hồ sơ</Button> : null}</DialogFooter></form></DialogContent></Dialog>;
}

export function DeletionRequestDialog({ target, open, pending, onOpenChange, onSubmit }: { target: { id: number; name: string } | null; open: boolean; pending: boolean; onOpenChange: (open: boolean) => void; onSubmit: (reason: string, evidenceFiles: File[]) => Promise<void> }) {
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-lg"><DeletionRequestForm target={target} pending={pending} onCancel={() => onOpenChange(false)} onSubmit={onSubmit} /></DialogContent></Dialog>;
}

export function DeletionRequestForm({ target, pending, onCancel, onSubmit }: { target: { id: number; name: string } | null; pending: boolean; onCancel: () => void; onSubmit: (reason: string, evidenceFiles: File[]) => Promise<void> }) {
  const [reason, setReason] = useState("");
  const [evidenceFiles, setEvidenceFiles] = useState<File[]>([]);
  useEffect(() => { setReason(""); setEvidenceFiles([]); }, [target?.id]);
  return <><DialogHeader><span className="mb-2 grid h-10 w-10 place-items-center rounded-xl bg-red-50 text-red-700"><MessageSquareWarning className="h-5 w-5" /></span><DialogTitle>Yêu cầu xóa hồ sơ</DialogTitle><DialogDescription>Hồ sơ <strong className="text-slate-800">{target?.name}</strong> sẽ không bị xóa ngay. Admin sẽ xem lý do, tài liệu minh chứng và quyết định xử lý.</DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label htmlFor="deletion-reason">Lý do yêu cầu xóa</Label><Textarea id="deletion-reason" value={reason} onChange={event => setReason(event.target.value)} placeholder="Nêu rõ lý do, ví dụ hồ sơ trùng hoặc nhập sai..." rows={5} maxLength={2000} /><p className="text-xs text-slate-500">Tối thiểu 10 ký tự. Thông tin này được lưu để Admin xem xét.</p></div><div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-3"><Label htmlFor="deletion-evidence" className="flex cursor-pointer items-center gap-2 text-sm font-semibold text-[#0b2f5b]"><Upload className="h-4 w-4" />Đính kèm tài liệu minh chứng<input id="deletion-evidence" className="hidden" type="file" accept="image/*,application/pdf" multiple onChange={event => { const files = Array.from(event.target.files ?? []); event.target.value = ""; const invalid = files.find(file => !(file.type.startsWith("image/") || file.type === "application/pdf") || file.size > 10 * 1024 * 1024); if (invalid) { toast.error("Chỉ nhận ảnh hoặc PDF, tối đa 10 MB mỗi tệp"); return; } setEvidenceFiles(current => [...current, ...files]); }} /></Label><p className="mt-1 text-xs text-slate-500">Có thể chọn nhiều ảnh hoặc PDF, tối đa 10 MB mỗi tệp.</p>{evidenceFiles.length ? <div className="mt-3 space-y-1.5">{evidenceFiles.map((file, index) => <div key={`${file.name}-${index}`} className="flex items-center justify-between gap-2 rounded-lg bg-white px-2.5 py-2 text-xs text-slate-700"><span className="truncate"><FileText className="mr-1.5 inline h-3.5 w-3.5 text-[#b91d3b]" />{file.name}</span><Button type="button" variant="ghost" size="icon" className="h-6 w-6 text-red-700" onClick={() => setEvidenceFiles(current => current.filter((_, itemIndex) => itemIndex !== index))}><X className="h-3.5 w-3.5" /></Button></div>)}</div> : null}</div></div><DialogFooter><Button type="button" variant="outline" onClick={onCancel}>Hủy</Button><Button type="button" className="bg-[#b91d3b] hover:bg-[#98142f]" disabled={pending || reason.trim().length < 10} onClick={() => void onSubmit(reason.trim(), evidenceFiles)}>{pending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <MessageSquareWarning className="mr-2 h-4 w-4" />}Gửi yêu cầu</Button></DialogFooter></>;
}

function SectionTitle({ title }: { title: string }) { return <div className="flex items-center gap-2"><span className="h-5 w-1 rounded-full bg-[#b91d3b]" /><h3 className="font-bold text-slate-900">{title}</h3></div>; }
function Field({ label, children, required, className = "" }: { label: string; children: React.ReactNode; required?: boolean; className?: string }) { return <div className={className}><Label className="mb-1.5 block text-xs font-semibold text-slate-600">{label}{required ? <span className="ml-0.5 text-red-700">*</span> : null}</Label>{children}</div>; }
export function FileUploadCard({ title, description, accept, disabled, onChange }: { title: string; description: string; accept: string; disabled: boolean; onChange: (event: ChangeEvent<HTMLInputElement>) => void }) { return <label className={`flex min-h-24 cursor-pointer flex-col justify-center rounded-xl border border-dashed border-slate-300 p-3 transition hover:border-[#0b2f5b] hover:bg-[#f8fbff] ${disabled ? "cursor-not-allowed opacity-50" : ""}`}><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#eef4fb] text-[#0b2f5b]"><Upload className="h-4 w-4" /></span><div><p className="text-xs font-bold text-slate-700">{title}</p><p className="mt-0.5 text-[11px] text-slate-500">{description}, tối đa 10MB</p></div></div><input disabled={disabled} type="file" accept={accept} className="hidden" onChange={onChange} /></label>; }
