import { PageHeader } from "@/components/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { trpc } from "@/lib/trpc";
import { ClipboardCheck, FileText, Search, ShieldAlert } from "lucide-react";
import { useState } from "react";

export default function PolicyPage() {
  const { data: units = [] } = trpc.units.list.useQuery();
  const [keyword, setKeyword] = useState("");
  const [unitId, setUnitId] = useState("all");
  const [filters, setFilters] = useState({ keyword: "", unitId: undefined as number | undefined, status: "inactive" as const });
  const { data: rows = [], isLoading } = trpc.personnel.list.useQuery(filters);
  const resolved = rows.filter(row => Boolean(row.policyResult?.trim())).length;
  return <div className="mx-auto w-full max-w-[1400px] space-y-6"><PageHeader eyebrow="Rà soát chế độ" title="Kết quả giải quyết chính sách" description="Hệ thống tự động tổng hợp các thành viên có trạng thái thôi tham gia để phục vụ tham mưu giải quyết chính sách." />
    <section className="grid gap-4 lg:grid-cols-[1fr_280px]"><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 sm:grid-cols-[1fr_220px_auto]"><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input className="h-11 pl-9" value={keyword} onChange={event => setKeyword(event.target.value)} onKeyDown={event => event.key === "Enter" && setFilters({ keyword, unitId: unitId === "all" ? undefined : Number(unitId), status: "inactive" })} placeholder="Họ tên, CCCD hoặc số điện thoại" /></div><Select value={unitId} onValueChange={setUnitId}><SelectTrigger className="h-11"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Tất cả đơn vị</SelectItem>{units.map(unit => <SelectItem key={unit.id} value={String(unit.id)}>{unit.name}</SelectItem>)}</SelectContent></Select><Button className="h-11 bg-[#0b2f5b] hover:bg-[#08274c]" onClick={() => setFilters({ keyword, unitId: unitId === "all" ? undefined : Number(unitId), status: "inactive" })}><Search className="mr-2 h-4 w-4" />Tra cứu</Button></div></div><aside className="rounded-2xl bg-[#0b2f5b] p-5 text-white shadow-lg shadow-[#0b2f5b]/20"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.13em] text-white/60">Hồ sơ thôi tham gia</p><p className="mt-2 text-3xl font-bold">{rows.length}</p></div><ShieldAlert className="h-6 w-6 text-[#f0bdc7]" /></div><div className="mt-5 border-t border-white/10 pt-4 text-sm text-white/70"><strong className="text-white">{resolved}</strong> hồ sơ đã cập nhật kết quả chính sách</div></aside></section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-bold text-slate-950">Danh sách cần rà soát</h2><p className="mt-0.5 text-sm text-slate-500">Chỉ hiển thị hồ sơ có ngày thôi tham gia.</p></div><Badge className="rounded-full bg-red-50 text-red-700 hover:bg-red-50"><ClipboardCheck className="mr-1.5 h-3.5 w-3.5" />Chính sách</Badge></div><div className="overflow-x-auto"><Table><TableHeader className="bg-slate-50"><TableRow><TableHead className="pl-5">Họ và tên</TableHead><TableHead>Đơn vị</TableHead><TableHead>Chức vụ</TableHead><TableHead>Ngày thôi tham gia</TableHead><TableHead>Thời gian CT</TableHead><TableHead className="pr-5">Kết quả chính sách</TableHead></TableRow></TableHeader><TableBody>{isLoading ? <TableRow><TableCell colSpan={6} className="h-36 text-center text-sm text-slate-500">Đang tải dữ liệu...</TableCell></TableRow> : null}{!isLoading && rows.length === 0 ? <TableRow><TableCell colSpan={6} className="h-48 text-center"><FileText className="mx-auto mb-3 h-8 w-8 text-slate-300" /><p className="font-medium text-slate-700">Chưa có hồ sơ thôi tham gia</p><p className="mt-1 text-sm text-slate-500">Danh sách sẽ tự động cập nhật khi cán bộ nhập ngày thôi tham gia trong hồ sơ.</p></TableCell></TableRow> : null}{rows.map(row => <TableRow className="border-slate-100" key={row.id}><TableCell className="pl-5 font-semibold text-slate-800">{row.fullName}</TableCell><TableCell className="text-slate-600">{row.unitName || "Chưa phân loại"}</TableCell><TableCell className="text-slate-600">{row.position || "—"}</TableCell><TableCell className="text-slate-600">{row.leftAt ? new Intl.DateTimeFormat("vi-VN").format(new Date(row.leftAt)) : "—"}</TableCell><TableCell className="text-slate-600">{row.serviceMonths ?? "—"}{row.serviceMonths !== null ? " tháng" : ""}</TableCell><TableCell className="max-w-md pr-5"><span className={row.policyResult ? "text-slate-700" : "italic text-slate-400"}>{row.policyResult || "Chưa cập nhật"}</span></TableCell></TableRow>)}</TableBody></Table></div></section></div>;
}
